#resolver: https://raw.githubusercontent.com/nikita-volkov/stack-snapshot/4163770ee93e3c3813a7289c843565d1b9ab98f0/snapshot.yaml
resolver: lts-19.23

extra-deps:
- jsonifier-0.2.0.1
- ptr-poker-0.1.2.5
