#resolver: https://raw.githubusercontent.com/nikita-volkov/stack-snapshot/4163770ee93e3c3813a7289c843565d1b9ab98f0/snapshot.yaml
resolver: lts-16.18

extra-deps:
- numeric-limits-0.1.0.0
- unordered-containers-0.2.13.0
- jsonifier-0.1.1
- ptr-poker-0.1.1.3
